### ISSUE TITLE
Accents problem

### ISSUE THREAD

**Issue by whann0205** [xaviersolau/BlazorJsonLocalization#13]
I have one component where i put 
{
  "Berechnen": "Calculate",
  "auswählen": "choose"
}
into the json file.
And although the Calculate Translation works perfectly for that page 
the choose get translated to three dots as you can in the screenshot
Any idea?
![grafik](https://user-images.githubusercontent.com/71807453/137326271-8a3832ec-2196-4597-816d-3c2f26d53e2d.png)

**Comment by xaviersolau** [comment]
Is it working if you use the key 'auswählen' without the accent like this auswahlen ?

**Comment by xaviersolau** [comment]
Well, this is an encoding issue. the Json files are UTF-8 encoded so if you want to use the `ä` character you must escape it like this: \u00e4.

In other words in your Json file you must write `auswählen` like this `ausw\u00e4hlen`.

see https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding for more information.

**Comment by whann0205** [comment]
Works like a charm.....great author....great library...
