### ISSUE TITLE
No actual value appears, only...

### ISSUE THREAD

**Issue by qcjxberin** [xaviersolau/BlazorJsonLocalization#18]
There is no actual value, only..., it is currently tested and used under WebAssembly.

**Comment by xaviersolau** [comment]
> There will be a little waiting time during the first loading. Is it possible to finish loading the language pack during this time?

Actually yes it is possible to pre-load the resources while initializing the application.
You can do it in your Program file like this:
instead of this:
```csharp
await builder.Build().RunAsync();
```
you can load the resources before the RunAsync:
```csharp
// build the host.
var host = builder.Build();

// Get the StringLocalizer and make sure it is loaded.
await host.Services.GetRequiredService<IStringLocalizer<Counter>>().LoadAsync();

// Run the app.
await host.RunAsync();
```

**Comment by xaviersolau** [comment]
> > In addition, is it possible to display the translation Key value instead of displaying when it is not loaded successfully, so that the entire page will not be displayed first by default... and then rendered
> 
> This can also be considered, it is suitable for displaying by default when the appropriate language pack data is not configured

I added an option in version 1.0.2-alpha.1 to display keys instead of ``...`` while loading asynchronously.

**Comment by qcjxberin** [comment]
Nice, thank you very much
