### ISSUE TITLE
Is it possible to put all the translation items in each language in one file

### ISSUE THREAD

**Issue by qcjxberin** [xaviersolau/BlazorJsonLocalization#19]
Is it possible to put all the translation items in each language in one file

**Comment by qcjxberin** [comment]
yes

**Comment by xaviersolau** [comment]
So why don't you use this solution?
Be the way, when I say a global IStringLocalizer I mean something like ``IStringLocalizer<MyGlobalClass>``.

**Comment by qcjxberin** [comment]
I’m already using it, I’m looking to see if there is a better way to implement it
