### ISSUE TITLE
Have you considered using cookies to dynamically set and get the current language

### ISSUE THREAD

**Issue by qcjxberin** [xaviersolau/BlazorJsonLocalization#22]
Have you considered using cookies to dynamically set and get the current language, that is to say, it is not entirely based on the language of the browser itself to call the language pack

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/140695359-d42140f0-3fb0-4c24-a230-475eb411374f.png)
Similar to the figure above, the default language of the current browser shall prevail. After switching, the language of the entire project shall be subject to the switched language.

**Comment by qcjxberin** [comment]
@xaviersolau

**Comment by xaviersolau** [comment]
Well, you can find in the repository 2 sample projects:
* One server side using cookies to store current language as explained in the Microsoft doc:
https://docs.microsoft.com/fr-fr/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#provide-ui-to-choose-the-culture
* One Client side (Wasm) using hard coded way to switch language.

Actually, you can store the language selection in cookies or in the local storage and load it at startup.

**Comment by qcjxberin** [comment]
So how to switch at runtime and also after the switch when refreshing?

**Comment by xaviersolau** [comment]
Basically, if you are using Blazor Wasm, one solution could be :
1. To set the ```CultureInfo``` static properties (like ```CultureInfo.DefaultThreadCurrentUICulture```) at startup from local storage.
2. Add a menu to define new language and store it in the storage.
3. Refresh the page using ```NavigationManager.NavigateTo("my current url", true);```

Or another solution could be to start from what I did in my sample:
https://github.com/xaviersolau/BlazorJsonLocalization/blob/main/src/examples/SoloX.BlazorJsonLocalization.Example.Wasm/Shared/MainLayout.razor

I updated the sample using local storage to save the selected language.

Hope this help.

**Comment by qcjxberin** [comment]
Thank you so much, your Demo is very clear

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/141236441-637f9441-73aa-432a-9d52-ff2c45cb04e0.png)
![image](https://user-images.githubusercontent.com/5792218/141236489-3d96b9c6-cb2e-43eb-a667-60b9c58e254d.png)
Under what circumstances will there be other calls that also need to be called?

**Comment by qcjxberin** [comment]
In addition, whether it can be configured globally, this way, the local storage is checked before obtaining the language pack. If the local storage is directly based on what is in the local storage, if not, it will be based on the browser default.

**Comment by qcjxberin** [comment]
@xaviersolau

**Comment by xaviersolau** [comment]
Well, I didn't catch it was a question.... Yes the sooner you can initialize the `CultureInfo.DefaultThreadCurrentUICulture` the better.
Actually in Blasor Wasm you can do it directly in the Program.cs since the local storage is already accessible.

```csharp
var host = builder.Build();

var localStorage = host.Services.GetRequiredService<ISyncLocalStorageService>();

if (localStorage.ContainKey(LanguageKey))
{
    var ci = CultureInfo.GetCultureInfo(localStorage.GetItemAsString(LanguageKey));
    CultureInfo.DefaultThreadCurrentUICulture = ci;
}
```

In this case you will also need to add a property in your application project file (csproj) unless you will get an exception:

```
<PropertyGroup>
  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
</PropertyGroup>
```

**Comment by qcjxberin** [comment]
Okay, another new problem is that it will call all language items through http. There should be a bug here, if it has already been called, then no other items should be called

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/141720170-6621fc74-e113-400f-9930-c457b1fca4c5.png)

**Comment by xaviersolau** [comment]
Is your project on github ? or could you provide some sample code to help me reproduce ?
The lib is also using logs... could you provide those application logs?

**Comment by qcjxberin** [comment]
Currently there is no newest project, but the problem is related to your last update. There is no problem with the previous version, but there will be problems after the upgrade.

**Comment by xaviersolau** [comment]
What version are you talking about? Is it the version `1.0.2-alpha.2`?
This version is actually using a new feature which is using parent culture hierarchy. Basically, it provides a fallback on the parent culture.
For example if a key is not present in the `Local-fr-FR.json` it will fall back to `Local-fr.json` and if it still don’t match the key it will fall back again to `Local.json`.
The fact is that in version `1.0.2-alpha.2` the LoadAsync was actually loading the whole parent hierarchy. (In my example: `Local-fr-FR.json`, `Local-fr.json` and `Local.json`)
I am planning (in version `1.0.2-alpha.4`) to change the behavior to make it optional in the LoadAsync method. So, in your case, it should be back to what you had in the previous version `1.0.2-alpha.1`.

_Note that in the loading process if a file is not found (404 error) for a given culture it will always try to load the parent culture file._

**Comment by qcjxberin** [comment]
Do I need to add any parameters to ensure that other language pack files will not be called? I currently use the latest code

**Comment by xaviersolau** [comment]
No you don't need to specify any parameters.
Could you provide the browser console logs?
Are you injecting the IStringLocalizer<Locale> outside a razor component?
I am suspecting that in some way a StringLocalizer is created before `CultureInfo.CurrentUICulture` is actually set to the right language.

I will update the lib to log what you get in the `CultureInfo.CurrentUICulture`. It may help to investigate.

**Comment by xaviersolau** [comment]
version 1.0.2-alpha.5 is available with additional logs to see what language is setup:

![image](https://user-images.githubusercontent.com/15972064/143506552-89677084-2aed-4293-b31f-98837a5ba6ee.png)

**Comment by qcjxberin** [comment]
What I currently suspect is that when a translation of the current language pack does not exist, other files will be called, whether it is possible to add a switch parameter that is not allowed to call other translation files

**Comment by xaviersolau** [comment]
Please, could you provide your logs with v alpha 5 ?
