### ISSUE TITLE
Does not find the translation files net maui preview 10 /net6

### ISSUE THREAD

**Issue by whann0205** [xaviersolau/BlazorJsonLocalization#29]
Since the structure substantiallly changed from net3.1 xamarin i am not sure, where to put
the translation files.
Its directly on the projects root
![grafik](https://user-images.githubusercontent.com/71807453/142914687-881b17cd-e03e-4e1d-87fb-2abe1ca75642.png)
![grafik](https://user-images.githubusercontent.com/71807453/142914815-caf91f0e-bf49-4378-ac2b-408b86836bfa.png)
But the lib does not see it...

[0:] SoloX.BlazorJsonLocalization.Services.Impl.EmbeddedJsonLocalizationExtensionService: Warning: Embedded File Locales/Pages/RecentSearches-en.json does not exist

Any idea ? using the latest alpha 1.0.2. alpha 4....

**Comment by xaviersolau** [comment]
Hello,
Looks like the files are not define as `EmbeddedResource`.

You should see something like this in your csproj:

```xml
<ItemGroup>
    <Content Remove="Locales\Pages\RecentSearches-en.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Locales\Pages\RecentSearches-en.json" />
  </ItemGroup>
```

**Comment by whann0205** [comment]
Hi,
Yep, that was the problem. I forgot to set the files to embedded and do not copy. 
Somehow forgot during the migration...
Perfectly running now on net maui / net6!!
