### ISSUE TITLE
Conflict when rendering same resource multiple times

### ISSUE THREAD

**Issue by jorgesoprani** [xaviersolau/BlazorJsonLocalization#33]
If I render the same component multiple times at the same time there is a conflict and only one of them loads correctly

**Comment by xaviersolau** [comment]
Is it web assembly or server side?

**Comment by xaviersolau** [comment]
Fix in progress #34

**Comment by xaviersolau** [comment]
Version [1.0.3-alpha.1](https://www.nuget.org/packages/SoloX.BlazorJsonLocalization/1.0.3-alpha.1) should fix this issue.

**Comment by jorgesoprani** [comment]
Sorry for not giving more details about it. It happens when using http hosted json.
Didn't see and error logs. It happens when it's not yet cached and the first load fails for some of the repeated components.

**Comment by xaviersolau** [comment]
Thanks for your contribution #35 ! it will be included in version 1.0.3-alpha.2!
