### ISSUE TITLE
Level limit in structured JSon resources?

### ISSUE THREAD

**Issue by PMJMendes** [xaviersolau/BlazorJsonLocalization#49]
Can't seem to get this to work with more than one level of nesting:

```
{
  "Dashboard": {
    "TITLE": "Message Dashboard",
    "List": {
      "MESSAGES": "Messages"
    }
  }
}
```

It won't even read the file, and by the time it gets to the code, it's injected a NullStringLocalizer.

Works fine with one level, though:

```
{
  "Dashboard": {
    "TITLE": "Message Dashboard"
  },
  "DashboardList": {
    "MESSAGES": "Messages"
  }
}
```

**Comment by xaviersolau** [comment]
Hi,

This is strange, I have a working example on my side with tree different way to access the values:

```razor
<p>
    @L.GetSubLocalizer("Dashboard")["TITLE"]
</p>
<p>
    @L.GetSubLocalizer("Dashboard").GetSubLocalizer("List")["MESSAGES"]
</p>
<p>
    @L[Key.Path("Dashboard", "TITLE")]
</p>
<p>
    @L[Key.Path("Dashboard", "List", "MESSAGES")]
</p>
<p>
    @L["Dashboard:TITLE"]
</p>
<p>
    @L["Dashboard:List:MESSAGES"]
</p>
```

It gives me:

![image](https://user-images.githubusercontent.com/15972064/217368902-7ef64185-e518-4762-a227-229676e5f654.png)

What version of the project do you use?

Can you drop a sample of your code?

**Comment by PMJMendes** [comment]
I downloaded your main branch.

Turns out, you're right, there must have been some other problem that I fixed in the meantime.

All's working now. :)

Thanks for keeping on top of things.
