### ISSUE TITLE
Raise warn and error when not finding "top" culture

### ISSUE THREAD

**Issue by m4ss1m0g** [xaviersolau/BlazorJsonLocalization#51]
## Scenario

- Type: WASM application
- Framework: net7.0

### Package version
`<PackageReference Include="SoloX.BlazorJsonLocalization.WebAssembly" Version="2.0.0-alpha.4" />`

### Setup

Code 

``` csharp

            services.AddJsonLocalization(
                builder => builder.UseEmbeddedJson(
                    options => options.ResourcesPath = "Resources")
                );

            var cultureInfo = CultureInfo.GetCultureInfo("en-US");
            CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
```

Folders structure

Features
---- Home
-------- HomePage.razor

Resources
---- Features
-------- Home
------------ HomePage-en-US.json

HomePage.razor

``` csharp
@inject IStringLocalizer<HomePage> L
```

### Console logging

![image](https://user-images.githubusercontent.com/4323707/232027688-26c1bc01-2bb2-412d-8351-84ea30a60cc7.png)

If I add HomePage-en.json and HomePage.json the result are pretty the same.

![image](https://user-images.githubusercontent.com/4323707/232028658-dc377be9-ca05-4c83-a7a0-91efbc54e3db.png)

**Comment by xaviersolau** [comment]
Thanks for providing the details.

Do you mean that `HomePage-en-US.json` is never loaded?

Was it working with previous version?

Could you provide your csproj file to check how json resources are declared?

**Comment by m4ss1m0g** [comment]
I found the issue, and I am sorry to bother you.
I haven't declared a label inside the json file, in this case I think the lib was looking at the entire tree to look for it.
I think adding the missing label to the log is a good thing.
Anyway, thanks for your fasten response and for the tool.
