### ISSUE TITLE
Use Json iStringLocalizer in controller

### ISSUE THREAD

**Issue by Giubel1976** [xaviersolau/BlazorJsonLocalization#59]
Hi,
I use the library on the WASM Blazor client with no problems. I have set the preferred language for each user on the database.
When I run services on the controller I should return errors and texts based on the language chosen by the user. Is it possible to instantiate the library by calling it manually by passing the json file directly to it?

Tk

**Comment by xaviersolau** [comment]
Hello,

I am not not sure to see what you want to do exactly but you can use it as you would do in the server-side project.
You can find an [example](https://github.com/xaviersolau/BlazorJsonLocalization/blob/bf77895e98d19375214a0230f202f9f0d3334682/src/examples/SoloX.BlazorJsonLocalization.Example.ServerSide/Startup.cs#L46) in the repo.

Is your API hosting the client or are your projects completely separated?

Are your Json files embedded or hosted?

you may find useful those examples:
* [embedded](https://github.com/xaviersolau/BlazorJsonLocalization/blob/main/src/examples/SoloX.BlazorJsonLocalization.Example.Components.Embedded/ComponentsEmbeddedExtensions.cs)
* [hosted](https://github.com/xaviersolau/BlazorJsonLocalization/blob/main/src/examples/SoloX.BlazorJsonLocalization.Example.Components.StaticAssets/ComponentsStaticAssetsExtensions.cs)

Hope this helps.
