### ISSUE TITLE
Use Key as fallback

### ISSUE THREAD

**Issue by Jimmys20** [xaviersolau/BlazorJsonLocalization#68]
Hello, is there a way to make localizer return the key string instead of "..." as a fallback when resources are not found? For example `@Localizer["Product"]` will return `"Product"` instead of `"..."` when no resources are found for the current culture.

**Comment by xaviersolau** [comment]
Hello,

Yes, you can use the `EnableDisplayKeysWhileLoadingAsynchronously()` method in the options builder.

For example on a server side application:

```
services.AddServerSideJsonLocalization(
    builder =>
    {
        builder.EnableDisplayKeysWhileLoadingAsynchronously();
    });

```
or on a Wasm application:

```
services.AddWebAssemblyJsonLocalization(
    builder =>
    {
        builder.EnableDisplayKeysWhileLoadingAsynchronously();
    });

```

Hope this helps!

**Comment by Jimmys20** [comment]
Yes, it does what I needed, thanks!
