### ISSUE TITLE
`await L.LoadAsync()` infinite loop with UseHttpHostedJson when Resources are 404 NotFound.

### ISSUE THREAD

**Issue by Jimmys20** [xaviersolau/BlazorJsonLocalization#76]
Hello, I'm trying to figure out how the libs fallback mechanism works when resources are missing. In the following example I'm using `UseHttpHostedJson` and locale is en-US but `Counter.en-US.json`, `Counter.en.json` or `Counter.json` are intentionally missing.

```csharp
builder.Services.AddWebAssemblyJsonLocalization(builder =>
{
    builder
      .EnableDisplayKeysWhileLoadingAsynchronously()
      .UseHttpHostedJson(options =>
      {
          options.ApplicationAssembly = typeof(Program).Assembly;
          options.ResourcesPath = "Resources";
      });
});
```
```razor
@page "/counter"
@using Microsoft.Extensions.Localization
@using SoloX.BlazorJsonLocalization
@implements IGlobal
@inject IStringLocalizer<Counter> L

<PageTitle>Counter</PageTitle>

<h1>@L["Counter"]</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
  private int currentCount = 0;

  protected override async Task OnInitializedAsync()
  {
    await L.LoadAsync();
  }

  private void IncrementCount()
  {
    currentCount++;
  }
}
```

**Behaviour:**

The ui freeze app is stuck in an infinite loop in method `JsonStringLocalizerAsync.LoadAsync()`. If `Counter.en-US.json` exists then the lib also fetches `IGlobal.en-US.json` based on inheritance..

**Expected Behaviour:**

 If `Counter.en-US.json`, `Counter.en.json` or `Counter.json` are missing, the lib should look for `IGlobal.en-US.json`,`IGlobal.en.json` and `IGlobal.json` and if those are missing too it should fallback to `EnableDisplayKeysWhileLoadingAsynchronously` and simply display the keys.

I suggest that the lib should try to fetch resources based on inheritance even when the resources for the derived type are missing.

**Scenario where I believe it would be useful:**

Let's say I have a base component `BaseComponent.cs` with some common functionality that needs localization so I create `BaseComponent.en-US.json` with the translations.

`BaseComponent` looks like this:

```
public class BaseComponent : ComponentBase
{
   [Inject]
   private IStringLocalizerFactory StringLocalizerFactory { get; set; }

   private IStringLocalizer _l;
   protected IStringLocalizer L => _l ??= StringLocalizerFactory.Create(GetType());
}
```

Then I have `Component1.razor`, `Component2.razor`, `Component3.razor` which extend `BaseComponent`. Some of the derived components can have some extra features that need localization but others don't. Right now I have to create at least an empty json resource for all derived types`Component1.en-US.json`, `Component2.en-US.json`, `Component3.en-US.json` etc. Instead if let's say `Component3.razor` doesn't have any extra functionality that needs localization other than the inherited, I would like to be able to ommit the `Component3.en-US.json` resource file and rely on the shared resource of the base type.

Demo: https://github.com/Jimmys20/BlazorJsonLocalizationDemo

**Comment by xaviersolau** [comment]
Thanks for reporting this issue.
I am going to investigate this issue. I will let you know soon.

**Comment by xaviersolau** [comment]
The fix will be in next release.

**Comment by xaviersolau** [comment]
It should be working with version 2.0.9.

**Comment by Jimmys20** [comment]
Yes, it works great! Thanks for fixing it so quickly.
